
import java.awt.Color;
import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author h_lah
 */
public class NewJFrame extends javax.swing.JFrame {

    int xMouse, yMouse;
    long FlujoTotal;
    long pausa;
    FileInputStream fis;
    BufferedInputStream bis;
    Player player;
    File file = null;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        this.setExtendedState(NORMAL);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_muroPersonal = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jd_muroPrincipal = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        reproductorPrincipal = new javax.swing.JButton();
        jd_createUser = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tf_nombreRegistrarU = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        tf_apellidoRegistrarU = new javax.swing.JTextField();
        tf_apodoRegistrarU = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        bt_registrarteU = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        pf_passwordConfirmU = new javax.swing.JPasswordField();
        pf_passwordCreateU = new javax.swing.JPasswordField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        sp_yearU = new javax.swing.JSpinner();
        header_register1 = new javax.swing.JPanel();
        pn_exitBttnRegister1 = new javax.swing.JPanel();
        lb_exitBttnRegister1 = new javax.swing.JLabel();
        sp_dateU = new javax.swing.JSpinner();
        sp_monthU = new javax.swing.JSpinner();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        tf_paisCreateU = new javax.swing.JTextField();
        reproductorMusical = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        reproductorTexto = new javax.swing.JLabel();
        AgregarMusica = new javax.swing.JButton();
        Play = new javax.swing.JButton();
        Pausa = new javax.swing.JButton();
        Stop = new javax.swing.JButton();
        jd_createAdmin = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        tf_nombreAdmin = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        tf_apellidoAdmin = new javax.swing.JTextField();
        tf_apodoAdmin = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        bt_registrarAdmin = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        pf_passwordConfirmAdmin = new javax.swing.JPasswordField();
        pf_passwordCreateAdmin = new javax.swing.JPasswordField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        sp_yearAdmin = new javax.swing.JSpinner();
        header_registerAdmin = new javax.swing.JPanel();
        pn_exitBttnAddAdmin = new javax.swing.JPanel();
        lb_exitBttnAddAdmin = new javax.swing.JLabel();
        sp_dateAdmin = new javax.swing.JSpinner();
        sp_monthAdmin = new javax.swing.JSpinner();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        tf_paisAdmin = new javax.swing.JTextField();
        panelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tf_username = new javax.swing.JTextField();
        bt_login = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        bt_CreateNewAccount = new javax.swing.JButton();
        pf_password = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pn_header = new javax.swing.JPanel();
        pn_exitBttn = new javax.swing.JPanel();
        lb_exitTxt = new javax.swing.JLabel();
        ingresarAdminsitrador = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Profile pic");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 120));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Amigos");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 150, 170));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("jLabel14");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 310, 310));

        jTextField1.setText("¿Qué estás pensando, usuario?");
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 300, 60));

        jButton6.setText("Agregar media");
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jButton7.setText("Publicar");
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        jButton8.setText("Editar perfil");
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel20.setText("Sugerencias de amigos");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 140, 190));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, 60));

        jButton1.setText("Reproductor Musical");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jButton2.setText("<-------");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel4.setText("Regresar Menu Principal");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        javax.swing.GroupLayout jd_muroPersonalLayout = new javax.swing.GroupLayout(jd_muroPersonal.getContentPane());
        jd_muroPersonal.getContentPane().setLayout(jd_muroPersonalLayout);
        jd_muroPersonalLayout.setHorizontalGroup(
            jd_muroPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_muroPersonalLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jd_muroPersonalLayout.setVerticalGroup(
            jd_muroPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_muroPersonalLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Profile pic");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 110, 70));

        jButton9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton9.setText("Ir a tu muro personal");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jPanel5.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Muro principal");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 360, 370));

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel19.setText("Sugerencias de amigos");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 140, 370));

        jTextField2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextField2.setText("¿Qué estás pensando, usuario?");
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 300, 60));

        jButton10.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton10.setText("Agregar media");
        jPanel5.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jButton11.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton11.setText("Publicar");
        jPanel5.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        reproductorPrincipal.setText("Reproductor Musical");
        reproductorPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reproductorPrincipalMouseClicked(evt);
            }
        });
        jPanel5.add(reproductorPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        javax.swing.GroupLayout jd_muroPrincipalLayout = new javax.swing.GroupLayout(jd_muroPrincipal.getContentPane());
        jd_muroPrincipal.getContentPane().setLayout(jd_muroPrincipalLayout);
        jd_muroPrincipalLayout.setHorizontalGroup(
            jd_muroPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_muroPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jd_muroPrincipalLayout.setVerticalGroup(
            jd_muroPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_muroPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jd_createUser.setUndecorated(true);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel25.setText("Registrarte");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Es rápido y fácil.");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        tf_nombreRegistrarU.setBackground(new java.awt.Color(243, 243, 255));
        tf_nombreRegistrarU.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tf_nombreRegistrarU.setForeground(new java.awt.Color(204, 204, 204));
        tf_nombreRegistrarU.setText("Nombre");
        tf_nombreRegistrarU.setBorder(null);
        tf_nombreRegistrarU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_nombreRegistrarUMouseClicked(evt);
            }
        });
        jPanel8.add(tf_nombreRegistrarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 168, 32));
        jPanel8.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 10));

        tf_apellidoRegistrarU.setBackground(new java.awt.Color(243, 243, 255));
        tf_apellidoRegistrarU.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tf_apellidoRegistrarU.setForeground(new java.awt.Color(204, 204, 204));
        tf_apellidoRegistrarU.setText("Apellido");
        tf_apellidoRegistrarU.setBorder(null);
        tf_apellidoRegistrarU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_apellidoRegistrarUMouseClicked(evt);
            }
        });
        jPanel8.add(tf_apellidoRegistrarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 181, 32));

        tf_apodoRegistrarU.setBackground(new java.awt.Color(243, 243, 255));
        tf_apodoRegistrarU.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tf_apodoRegistrarU.setForeground(new java.awt.Color(204, 204, 204));
        tf_apodoRegistrarU.setText("Apodo");
        tf_apodoRegistrarU.setBorder(null);
        tf_apodoRegistrarU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_apodoRegistrarUMouseClicked(evt);
            }
        });
        jPanel8.add(tf_apodoRegistrarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 370, 40));

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel27.setText("País");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 35, -1));

        jLabel28.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel28.setText("Año");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        bt_registrarteU.setBackground(new java.awt.Color(0, 177, 0));
        bt_registrarteU.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bt_registrarteU.setForeground(new java.awt.Color(255, 255, 255));
        bt_registrarteU.setText("Registrarte");
        bt_registrarteU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_registrarteU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarteUMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_registrarteUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_registrarteUMouseExited(evt);
            }
        });
        jPanel8.add(bt_registrarteU, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 181, 42));

        jLabel29.setBackground(new java.awt.Color(204, 204, 204));
        jLabel29.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 153, 153));
        jLabel29.setText("Al hacer clic en \"Registrarte\", aceptas nuestras Condiciones la politica de privacidad ");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jLabel30.setBackground(new java.awt.Color(204, 204, 204));
        jLabel30.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(153, 153, 153));
        jLabel30.setText("y la Política de cookies.");
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        pf_passwordConfirmU.setForeground(new java.awt.Color(204, 204, 204));
        pf_passwordConfirmU.setText("Contraseña");
        pf_passwordConfirmU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pf_passwordConfirmUMouseClicked(evt);
            }
        });
        jPanel8.add(pf_passwordConfirmU, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 160, 30));

        pf_passwordCreateU.setForeground(new java.awt.Color(204, 204, 204));
        pf_passwordCreateU.setText("Contraseña");
        pf_passwordCreateU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pf_passwordCreateUMouseClicked(evt);
            }
        });
        jPanel8.add(pf_passwordCreateU, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 150, 30));

        jLabel32.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel32.setText("Ingresa tu contraseña: ");
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel33.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel33.setText("Confirma tu contraseña: ");
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        sp_yearU.setModel(new javax.swing.SpinnerNumberModel(1900, 1900, 2024, 1));
        jPanel8.add(sp_yearU, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        header_register1.setBackground(new java.awt.Color(255, 255, 255));
        header_register1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header_register1MouseDragged(evt);
            }
        });
        header_register1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header_register1MousePressed(evt);
            }
        });

        pn_exitBttnRegister1.setBackground(new java.awt.Color(255, 255, 255));

        lb_exitBttnRegister1.setBackground(new java.awt.Color(255, 255, 255));
        lb_exitBttnRegister1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_exitBttnRegister1.setText("X");
        lb_exitBttnRegister1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_exitBttnRegister1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_exitBttnRegister1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_exitBttnRegister1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_exitBttnRegister1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_exitBttnRegister1Layout = new javax.swing.GroupLayout(pn_exitBttnRegister1);
        pn_exitBttnRegister1.setLayout(pn_exitBttnRegister1Layout);
        pn_exitBttnRegister1Layout.setHorizontalGroup(
            pn_exitBttnRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_exitBttnRegister1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_exitBttnRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pn_exitBttnRegister1Layout.setVerticalGroup(
            pn_exitBttnRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exitBttnRegister1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout header_register1Layout = new javax.swing.GroupLayout(header_register1);
        header_register1.setLayout(header_register1Layout);
        header_register1Layout.setHorizontalGroup(
            header_register1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_register1Layout.createSequentialGroup()
                .addGap(0, 471, Short.MAX_VALUE)
                .addComponent(pn_exitBttnRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        header_register1Layout.setVerticalGroup(
            header_register1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_exitBttnRegister1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.add(header_register1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 30));

        sp_dateU.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        jPanel8.add(sp_dateU, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        sp_monthU.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        sp_monthU.setModel(new javax.swing.SpinnerListModel(new String[] {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"}));
        jPanel8.add(sp_monthU, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 100, -1));

        jLabel34.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel34.setText("Fecha de Nacimiento");
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel35.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel35.setText("Día");
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel36.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel36.setText("Mes");
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        tf_paisCreateU.setBackground(new java.awt.Color(243, 243, 255));
        tf_paisCreateU.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tf_paisCreateU.setForeground(new java.awt.Color(204, 204, 204));
        tf_paisCreateU.setText("País o región");
        tf_paisCreateU.setBorder(null);
        tf_paisCreateU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_paisCreateUMouseClicked(evt);
            }
        });
        jPanel8.add(tf_paisCreateU, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 250, 30));

        javax.swing.GroupLayout jd_createUserLayout = new javax.swing.GroupLayout(jd_createUser.getContentPane());
        jd_createUser.getContentPane().setLayout(jd_createUserLayout);
        jd_createUserLayout.setHorizontalGroup(
            jd_createUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jd_createUserLayout.setVerticalGroup(
            jd_createUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        reproductorTexto.setBackground(new java.awt.Color(255, 255, 255));
        reproductorTexto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        AgregarMusica.setText("AgregarCancion");
        AgregarMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AgregarMusicaMouseReleased(evt);
            }
        });

        Play.setText("Play");
        Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PlayMouseReleased(evt);
            }
        });

        Pausa.setText("Pause");
        Pausa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PausaMouseReleased(evt);
            }
        });

        Stop.setText("Stop");
        Stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                StopMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(Stop)
                .addGap(28, 28, 28)
                .addComponent(Play, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Pausa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(AgregarMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reproductorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(reproductorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarMusica)
                    .addComponent(Play)
                    .addComponent(Pausa)
                    .addComponent(Stop))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout reproductorMusicalLayout = new javax.swing.GroupLayout(reproductorMusical.getContentPane());
        reproductorMusical.getContentPane().setLayout(reproductorMusicalLayout);
        reproductorMusicalLayout.setHorizontalGroup(
            reproductorMusicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        reproductorMusicalLayout.setVerticalGroup(
            reproductorMusicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jd_createAdmin.setUndecorated(true);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel37.setText("Registrar administrador");
        jPanel9.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel38.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setText("Es rápido y fácil.");
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        tf_nombreAdmin.setBackground(new java.awt.Color(243, 243, 255));
        tf_nombreAdmin.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tf_nombreAdmin.setForeground(new java.awt.Color(204, 204, 204));
        tf_nombreAdmin.setText("Nombre");
        tf_nombreAdmin.setBorder(null);
        tf_nombreAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_nombreAdminMouseClicked(evt);
            }
        });
        jPanel9.add(tf_nombreAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 168, 32));
        jPanel9.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 210, 10));

        tf_apellidoAdmin.setBackground(new java.awt.Color(243, 243, 255));
        tf_apellidoAdmin.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tf_apellidoAdmin.setForeground(new java.awt.Color(204, 204, 204));
        tf_apellidoAdmin.setText("Apellido");
        tf_apellidoAdmin.setBorder(null);
        tf_apellidoAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_apellidoAdminMouseClicked(evt);
            }
        });
        jPanel9.add(tf_apellidoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 181, 32));

        tf_apodoAdmin.setBackground(new java.awt.Color(243, 243, 255));
        tf_apodoAdmin.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tf_apodoAdmin.setForeground(new java.awt.Color(204, 204, 204));
        tf_apodoAdmin.setText("Apodo");
        tf_apodoAdmin.setBorder(null);
        tf_apodoAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_apodoAdminMouseClicked(evt);
            }
        });
        jPanel9.add(tf_apodoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 370, 40));

        jLabel39.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel39.setText("País");
        jPanel9.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 35, -1));

        jLabel40.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel40.setText("Año");
        jPanel9.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        bt_registrarAdmin.setBackground(new java.awt.Color(0, 177, 0));
        bt_registrarAdmin.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        bt_registrarAdmin.setForeground(new java.awt.Color(255, 255, 255));
        bt_registrarAdmin.setText("Registrar");
        bt_registrarAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_registrarAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_registrarAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_registrarAdminMouseExited(evt);
            }
        });
        jPanel9.add(bt_registrarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 181, 42));

        jLabel41.setBackground(new java.awt.Color(204, 204, 204));
        jLabel41.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(153, 153, 153));
        jLabel41.setText("Al hacer clic en \"Registrar\", el administrador nuevo acepta nuestros ");
        jPanel9.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jLabel42.setBackground(new java.awt.Color(204, 204, 204));
        jLabel42.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(153, 153, 153));
        jLabel42.setText("Términos y Condiciones aplicables a administradores.");
        jPanel9.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        pf_passwordConfirmAdmin.setForeground(new java.awt.Color(204, 204, 204));
        pf_passwordConfirmAdmin.setText("Contraseña");
        pf_passwordConfirmAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pf_passwordConfirmAdminMouseClicked(evt);
            }
        });
        jPanel9.add(pf_passwordConfirmAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 160, 30));

        pf_passwordCreateAdmin.setForeground(new java.awt.Color(204, 204, 204));
        pf_passwordCreateAdmin.setText("Contraseña");
        pf_passwordCreateAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pf_passwordCreateAdminMouseClicked(evt);
            }
        });
        jPanel9.add(pf_passwordCreateAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 150, 30));

        jLabel44.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel44.setText("Ingresa tu contraseña: ");
        jPanel9.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel45.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel45.setText("Confirma tu contraseña: ");
        jPanel9.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        sp_yearAdmin.setModel(new javax.swing.SpinnerNumberModel(1900, 1900, 2024, 1));
        jPanel9.add(sp_yearAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        header_registerAdmin.setBackground(new java.awt.Color(255, 255, 255));
        header_registerAdmin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header_registerAdminMouseDragged(evt);
            }
        });
        header_registerAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header_registerAdminMousePressed(evt);
            }
        });

        pn_exitBttnAddAdmin.setBackground(new java.awt.Color(255, 255, 255));

        lb_exitBttnAddAdmin.setBackground(new java.awt.Color(255, 255, 255));
        lb_exitBttnAddAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_exitBttnAddAdmin.setText("X");
        lb_exitBttnAddAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_exitBttnAddAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_exitBttnAddAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_exitBttnAddAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_exitBttnAddAdminMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_exitBttnAddAdminLayout = new javax.swing.GroupLayout(pn_exitBttnAddAdmin);
        pn_exitBttnAddAdmin.setLayout(pn_exitBttnAddAdminLayout);
        pn_exitBttnAddAdminLayout.setHorizontalGroup(
            pn_exitBttnAddAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_exitBttnAddAdminLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_exitBttnAddAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pn_exitBttnAddAdminLayout.setVerticalGroup(
            pn_exitBttnAddAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exitBttnAddAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout header_registerAdminLayout = new javax.swing.GroupLayout(header_registerAdmin);
        header_registerAdmin.setLayout(header_registerAdminLayout);
        header_registerAdminLayout.setHorizontalGroup(
            header_registerAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_registerAdminLayout.createSequentialGroup()
                .addGap(0, 471, Short.MAX_VALUE)
                .addComponent(pn_exitBttnAddAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        header_registerAdminLayout.setVerticalGroup(
            header_registerAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_exitBttnAddAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel9.add(header_registerAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 30));

        sp_dateAdmin.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        jPanel9.add(sp_dateAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        sp_monthAdmin.setModel(new javax.swing.SpinnerListModel(new String[] {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"}));
        jPanel9.add(sp_monthAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 100, -1));

        jLabel46.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel46.setText("Fecha de Nacimiento");
        jPanel9.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel47.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel47.setText("Día");
        jPanel9.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel48.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel48.setText("Mes");
        jPanel9.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        tf_paisAdmin.setBackground(new java.awt.Color(243, 243, 255));
        tf_paisAdmin.setForeground(new java.awt.Color(204, 204, 204));
        tf_paisAdmin.setText("País o región");
        tf_paisAdmin.setBorder(null);
        tf_paisAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_paisAdminMouseClicked(evt);
            }
        });
        jPanel9.add(tf_paisAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 250, 30));

        javax.swing.GroupLayout jd_createAdminLayout = new javax.swing.GroupLayout(jd_createAdmin.getContentPane());
        jd_createAdmin.getContentPane().setLayout(jd_createAdminLayout);
        jd_createAdminLayout.setHorizontalGroup(
            jd_createAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jd_createAdminLayout.setVerticalGroup(
            jd_createAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(240, 242, 245));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tf_username.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tf_username.setForeground(new java.awt.Color(204, 204, 204));
        tf_username.setText("Usuario");
        tf_username.setBorder(null);
        tf_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tf_usernameMousePressed(evt);
            }
        });

        bt_login.setBackground(new java.awt.Color(0, 102, 255));
        bt_login.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        bt_login.setForeground(new java.awt.Color(255, 255, 255));
        bt_login.setText("Iniciar sesión");
        bt_login.setBorder(null);
        bt_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_loginMouseExited(evt);
            }
        });
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });

        bt_CreateNewAccount.setBackground(new java.awt.Color(0, 188, 3));
        bt_CreateNewAccount.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        bt_CreateNewAccount.setForeground(new java.awt.Color(255, 255, 255));
        bt_CreateNewAccount.setText("Crear cuenta nueva");
        bt_CreateNewAccount.setBorder(null);
        bt_CreateNewAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_CreateNewAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_CreateNewAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_CreateNewAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_CreateNewAccountMouseExited(evt);
            }
        });

        pf_password.setForeground(new java.awt.Color(204, 204, 204));
        pf_password.setText("Contraseña");
        pf_password.setBorder(null);
        pf_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pf_passwordMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pf_password, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(tf_username)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(bt_CreateNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(bt_CreateNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        panelPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Facebook te ayuda a comunicarte y");
        panelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("compartir con las personas que forman");
        panelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("parte de tu vida.");
        panelPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/facebook logo2.png"))); // NOI18N
        panelPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        pn_header.setBackground(new java.awt.Color(240, 242, 255));
        pn_header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pn_headerMouseDragged(evt);
            }
        });
        pn_header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pn_headerMousePressed(evt);
            }
        });

        pn_exitBttn.setBackground(new java.awt.Color(240, 242, 255));

        lb_exitTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lb_exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_exitTxt.setText("X");
        lb_exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_exitBttnLayout = new javax.swing.GroupLayout(pn_exitBttn);
        pn_exitBttn.setLayout(pn_exitBttnLayout);
        pn_exitBttnLayout.setHorizontalGroup(
            pn_exitBttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exitTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );
        pn_exitBttnLayout.setVerticalGroup(
            pn_exitBttnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exitTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_headerLayout = new javax.swing.GroupLayout(pn_header);
        pn_header.setLayout(pn_headerLayout);
        pn_headerLayout.setHorizontalGroup(
            pn_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_headerLayout.createSequentialGroup()
                .addGap(0, 888, Short.MAX_VALUE)
                .addComponent(pn_exitBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pn_headerLayout.setVerticalGroup(
            pn_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_exitBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelPrincipal.add(pn_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 30));

        ingresarAdminsitrador.setText("Iniciar como Administrador");
        panelPrincipal.add(ingresarAdminsitrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_CreateNewAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CreateNewAccountMouseClicked
        jd_createUser.setModal(true);
        jd_createUser.pack();
        jd_createUser.setLocationRelativeTo(null);
        jd_createUser.setVisible(true);

    }//GEN-LAST:event_bt_CreateNewAccountMouseClicked

    private void lb_exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lb_exitTxtMouseClicked

    private void lb_exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitTxtMouseEntered
        pn_exitBttn.setBackground(Color.red);
        lb_exitTxt.setForeground(Color.white);

    }//GEN-LAST:event_lb_exitTxtMouseEntered

    private void lb_exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitTxtMouseExited
        pn_exitBttn.setBackground(new Color(240, 242, 255));
        lb_exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_lb_exitTxtMouseExited

    private void pn_headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pn_headerMousePressed

    private void pn_headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_pn_headerMouseDragged

    private void tf_usernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_usernameMousePressed
        if (tf_username.getText().equals("Usuario")) {
            tf_username.setText("");
            tf_username.setForeground(Color.black);
        }
        if (pf_password.getText().equals("")) {
            pf_password.setText("Contraseña");
            pf_password.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_tf_usernameMousePressed

    private void pf_passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pf_passwordMousePressed
        if (pf_password.getText().equals("Contraseña")) {
            pf_password.setText("");
            pf_password.setForeground(Color.black);
        }
        if (tf_username.getText().equals("")) {
            tf_username.setText("Usuario");
            tf_username.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_pf_passwordMousePressed

    private void bt_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseExited
        bt_login.setBackground(new Color(0, 10, 255));
    }//GEN-LAST:event_bt_loginMouseExited

    private void bt_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseEntered
        bt_login.setBackground(new Color(0, 70, 255));
    }//GEN-LAST:event_bt_loginMouseEntered

    private void bt_CreateNewAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CreateNewAccountMouseEntered
        bt_CreateNewAccount.setBackground(new Color(0, 180, 0));
    }//GEN-LAST:event_bt_CreateNewAccountMouseEntered

    private void bt_CreateNewAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CreateNewAccountMouseExited
        bt_CreateNewAccount.setBackground(new Color(0, 204, 0));
    }//GEN-LAST:event_bt_CreateNewAccountMouseExited

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
//        if (tf_username.getText().equals("admin") && pf_password.getText().equals("1234")) {
//            this.setVisible(false);
//            jd_muroPrincipal.setVisible(true);
//            jd_muroPrincipal.pack();
//            jd_muroPrincipal.setLocationRelativeTo(null);
//
//        } else {
//            JOptionPane.showMessageDialog(this, "Usuario no Encontrado");
//        }
    }//GEN-LAST:event_bt_loginActionPerformed

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        jd_muroPrincipal.setLocationRelativeTo(null);
        jd_muroPrincipal.pack();
        jd_muroPrincipal.setVisible(true);

    }//GEN-LAST:event_jLabel24MouseClicked

    private void bt_registrarteUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarteUMouseClicked
        int dia;
        int mes;
        int anio;
        String mesFromSp = sp_monthU.getValue().toString();

        if (mesFromSp.equals("Enero")) {
            mes = 0;
        } else if (mesFromSp.equals("Febrero")) {
            mes = 1;
        } else if (mesFromSp.equals("Marzo")) {
            mes = 2;
        } else if (mesFromSp.equals("Abril")) {
            mes = 3;
        } else if (mesFromSp.equals("Mayo")) {
            mes = 4;
        } else if (mesFromSp.equals("Junio")) {
            mes = 5;
        } else if (mesFromSp.equals("Julio")) {
            mes = 6;
        } else if (mesFromSp.equals("Agosto")) {
            mes = 7;
        } else if (mesFromSp.equals("Septiembre")) {
            mes = 8;
        } else if (mesFromSp.equals("Octubre")) {
            mes = 9;
        } else if (mesFromSp.equals("Noviembre")) {
            mes = 10;
        } else {
            mes = 11;
        }

        if (pf_passwordCreateU.getText().equals(pf_passwordConfirmU.getText())) {
            dia = Integer.parseInt(sp_dateU.getValue().toString());
            anio = Integer.parseInt(sp_yearU.getValue().toString());
            Usuario p = new Regular((tf_nombreRegistrarU.getText() + " " + tf_apellidoRegistrarU.getText()),
                    tf_apodoRegistrarU.getText(),
                    pf_password.getText(),
                    tf_paisCreateU.getText(),
                    new Date(dia, mes, anio));
            administradorUsuario admin = new administradorUsuario("./UsuariosRegulares.pfb");
            admin.cargarArchivo();
            admin.setPersona(p);
            admin.escribirArchivo();
            JOptionPane.showMessageDialog(jd_createUser, "Bienvenido a Facebook "
                    + tf_nombreRegistrarU.getText() + "!");
            tf_nombreRegistrarU.setText("");
            tf_nombreRegistrarU.setForeground(Color.gray);
            tf_apellidoRegistrarU.setText("");
            tf_apellidoRegistrarU.setForeground(Color.gray);
            tf_apodoRegistrarU.setText("");
            tf_apodoRegistrarU.setForeground(Color.gray);
            tf_paisCreateU.setText("");
            tf_paisCreateU.setForeground(Color.gray);
            pf_passwordCreateU.setText("");
            pf_passwordCreateU.setForeground(Color.gray);
            pf_passwordConfirmU.setText("");
            pf_passwordConfirmU.setForeground(Color.gray);

            LlenarEspacios();
            jd_createUser.dispose();
        } else {
            JOptionPane.showMessageDialog(jd_createUser, "Las contraseñas "
                    + "ingresadas no son iguales. Intente otra vez.");
        }

    }//GEN-LAST:event_bt_registrarteUMouseClicked

    private void bt_registrarteUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarteUMouseEntered
        bt_registrarteU.setBackground(new Color(0, 155, 0));
    }//GEN-LAST:event_bt_registrarteUMouseEntered

    private void bt_registrarteUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarteUMouseExited
        bt_registrarteU.setBackground(new Color(0, 177, 0));
    }//GEN-LAST:event_bt_registrarteUMouseExited

    private void pf_passwordConfirmUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pf_passwordConfirmUMouseClicked
        LlenarEspacios();

        if (pf_passwordConfirmU.getText().equals("Contraseña")) {
            pf_passwordConfirmU.setText("");
            pf_passwordConfirmU.setForeground(Color.black);
        }
    }//GEN-LAST:event_pf_passwordConfirmUMouseClicked

    private void pf_passwordCreateUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pf_passwordCreateUMouseClicked
        LlenarEspacios();

        if (pf_passwordCreateU.getText().equals("Contraseña")) {
            pf_passwordCreateU.setText("");
            pf_passwordCreateU.setForeground(Color.black);
        }
    }//GEN-LAST:event_pf_passwordCreateUMouseClicked

    private void lb_exitBttnRegister1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitBttnRegister1MouseClicked
        jd_createUser.dispose();
    }//GEN-LAST:event_lb_exitBttnRegister1MouseClicked

    private void lb_exitBttnRegister1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitBttnRegister1MouseEntered
        pn_exitBttnRegister1.setBackground(Color.red);
        lb_exitBttnRegister1.setForeground(Color.white);
    }//GEN-LAST:event_lb_exitBttnRegister1MouseEntered

    private void lb_exitBttnRegister1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitBttnRegister1MouseExited
        pn_exitBttnRegister1.setBackground(Color.white);
        lb_exitBttnRegister1.setForeground(Color.black);
    }//GEN-LAST:event_lb_exitBttnRegister1MouseExited

    private void header_register1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_register1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        jd_createUser.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_header_register1MouseDragged

    private void header_register1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_register1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_header_register1MousePressed

    private void tf_nombreAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_nombreAdminMouseClicked
        LlenarEspaciosAdmin();
        if (tf_nombreAdmin.getText().equals("Nombre")) {
            tf_nombreAdmin.setText("");
            tf_nombreAdmin.setForeground(Color.black);
        }
    }//GEN-LAST:event_tf_nombreAdminMouseClicked

    private void bt_registrarAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarAdminMouseClicked
        int dia;
        int mes;
        int anio;
        String mesFromSp = sp_monthAdmin.getValue().toString();

        if (mesFromSp.equals("Enero")) {
            mes = 0;
        } else if (mesFromSp.equals("Febrero")) {
            mes = 1;
        } else if (mesFromSp.equals("Marzo")) {
            mes = 2;
        } else if (mesFromSp.equals("Abril")) {
            mes = 3;
        } else if (mesFromSp.equals("Mayo")) {
            mes = 4;
        } else if (mesFromSp.equals("Junio")) {
            mes = 5;
        } else if (mesFromSp.equals("Julio")) {
            mes = 6;
        } else if (mesFromSp.equals("Agosto")) {
            mes = 7;
        } else if (mesFromSp.equals("Septiembre")) {
            mes = 8;
        } else if (mesFromSp.equals("Octubre")) {
            mes = 9;
        } else if (mesFromSp.equals("Noviembre")) {
            mes = 10;
        } else {
            mes = 11;
        }

        if (pf_passwordCreateAdmin.getText().equals(pf_passwordConfirmAdmin.getText())) {
            dia = Integer.parseInt(sp_dateAdmin.getValue().toString());
            anio = Integer.parseInt(sp_yearAdmin.getValue().toString());
            Usuario p = new Administrador((tf_nombreAdmin.getText() + " " + tf_apellidoAdmin.getText()),
                    tf_apodoAdmin.getText(),
                    pf_passwordCreateAdmin.getText(),
                    tf_paisAdmin.getText(),
                    new Date(dia, mes, anio));
            administradorUsuario admin = new administradorUsuario("./UsuariosAdmin.pfb");
            admin.cargarArchivo();
            admin.setPersona(p);
            admin.escribirArchivo();
            JOptionPane.showMessageDialog(jd_createAdmin, "Administrador creado exitosamente");
            tf_nombreAdmin.setText("Nombre");
            tf_nombreAdmin.setForeground(Color.gray);
            tf_apellidoAdmin.setText("Apellido");
            tf_apellidoAdmin.setForeground(Color.gray);
            tf_apodoAdmin.setText("Apodo");
            tf_apodoAdmin.setForeground(Color.gray);
            tf_paisAdmin.setText("País o región");
            tf_paisAdmin.setForeground(Color.gray);
            pf_passwordCreateAdmin.setText("Contrasña");
            pf_passwordCreateAdmin.setForeground(Color.gray);
            pf_passwordConfirmAdmin.setText("Contraseña");
            pf_passwordConfirmAdmin.setForeground(Color.gray);
            
            jd_createAdmin.dispose();
        } else {
            JOptionPane.showMessageDialog(jd_createAdmin, "Las contraseñas "
                    + "ingresadas no son iguales. Intente otra vez.");
        }
    }//GEN-LAST:event_bt_registrarAdminMouseClicked

    private void bt_registrarAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarAdminMouseEntered
        bt_registrarAdmin.setBackground(new Color(0, 155, 0));
    }//GEN-LAST:event_bt_registrarAdminMouseEntered

    private void bt_registrarAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarAdminMouseExited
        bt_registrarAdmin.setBackground(new Color(0, 177, 0));
    }//GEN-LAST:event_bt_registrarAdminMouseExited

    private void pf_passwordConfirmAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pf_passwordConfirmAdminMouseClicked
        LlenarEspaciosAdmin();

        if (pf_passwordConfirmAdmin.getText().equals("Contraseña")) {
            pf_passwordConfirmAdmin.setText("");
            pf_passwordConfirmAdmin.setForeground(Color.black);
        }
    }//GEN-LAST:event_pf_passwordConfirmAdminMouseClicked

    private void pf_passwordCreateAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pf_passwordCreateAdminMouseClicked
        LlenarEspaciosAdmin();

        if (pf_passwordCreateAdmin.getText().equals("Contraseña")) {
            pf_passwordCreateAdmin.setText("");
            pf_passwordCreateAdmin.setForeground(Color.black);
        }
    }//GEN-LAST:event_pf_passwordCreateAdminMouseClicked

    private void lb_exitBttnAddAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitBttnAddAdminMouseClicked
        jd_createAdmin.dispose();
    }//GEN-LAST:event_lb_exitBttnAddAdminMouseClicked

    private void lb_exitBttnAddAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitBttnAddAdminMouseEntered
        pn_exitBttnAddAdmin.setBackground(Color.red);
        lb_exitBttnAddAdmin.setForeground(Color.white);
    }//GEN-LAST:event_lb_exitBttnAddAdminMouseEntered

    private void lb_exitBttnAddAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitBttnAddAdminMouseExited
        pn_exitBttnAddAdmin.setBackground(Color.white);
        lb_exitBttnAddAdmin.setForeground(Color.black);
    }//GEN-LAST:event_lb_exitBttnAddAdminMouseExited

    private void header_registerAdminMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_registerAdminMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        jd_createAdmin.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_header_registerAdminMouseDragged

    private void header_registerAdminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header_registerAdminMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_header_registerAdminMousePressed

    private void tf_nombreRegistrarUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_nombreRegistrarUMouseClicked
        LlenarEspacios();

        if (tf_nombreRegistrarU.getText().equals("Nombre")) {
            tf_nombreRegistrarU.setText("");
            tf_nombreRegistrarU.setForeground(Color.black);
        }
    }//GEN-LAST:event_tf_nombreRegistrarUMouseClicked

    private void tf_apellidoRegistrarUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_apellidoRegistrarUMouseClicked
        LlenarEspacios();

        if (tf_apellidoRegistrarU.getText().equals("Apellido")) {
            tf_apellidoRegistrarU.setText("");
            tf_apellidoRegistrarU.setForeground(Color.black);
        }
    }//GEN-LAST:event_tf_apellidoRegistrarUMouseClicked

    private void tf_apellidoAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_apellidoAdminMouseClicked
        LlenarEspaciosAdmin();

        if (tf_apellidoAdmin.getText().equals("Apellido")) {
            tf_apellidoAdmin.setText("");
            tf_apellidoAdmin.setForeground(Color.black);
        }
    }//GEN-LAST:event_tf_apellidoAdminMouseClicked

    private void tf_apodoAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_apodoAdminMouseClicked
        LlenarEspaciosAdmin();

        if (tf_apodoAdmin.getText().equals("Apodo")) {
            tf_apodoAdmin.setText("");
            tf_apodoAdmin.setForeground(Color.black);
        }
    }//GEN-LAST:event_tf_apodoAdminMouseClicked

    private void tf_apodoRegistrarUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_apodoRegistrarUMouseClicked
        LlenarEspacios();

        if (tf_apodoRegistrarU.getText().equals("Apodo")) {
            tf_apodoRegistrarU.setText("");
            tf_apodoRegistrarU.setForeground(Color.black);
        }
    }//GEN-LAST:event_tf_apodoRegistrarUMouseClicked

    private void tf_paisCreateUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_paisCreateUMouseClicked
        LlenarEspacios();

        if (tf_paisCreateU.getText().equals("País o región")) {
            tf_paisCreateU.setText("");
            tf_paisCreateU.setForeground(Color.black);
        }
    }//GEN-LAST:event_tf_paisCreateUMouseClicked

    private void tf_paisAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_paisAdminMouseClicked
        LlenarEspaciosAdmin();

        if (tf_paisAdmin.getText().equals("País o región")) {
            tf_paisAdmin.setText("");
            tf_paisAdmin.setForeground(Color.black);
        }
    }//GEN-LAST:event_tf_paisAdminMouseClicked

    private void AgregarMusicaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMusicaMouseReleased
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Audio", "mp3", "Mp3", "wav", "Wav");
        chooser.setFileFilter(filtro);
        int valor = chooser.showOpenDialog(null);
        if (valor == JFileChooser.CANCEL_OPTION) {
        } else {
            if (valor == JFileChooser.APPROVE_OPTION) {
                file = chooser.getSelectedFile();
                if (file == null) {
                } else {
                    String cancion = file + "";
                    String nombre = chooser.getSelectedFile().getName();
                    reproductorTexto.setText(nombre);
                }
            }
            try {
                if (file == null) {
                } else {
                    fis = new FileInputStream(file);
                    bis = new BufferedInputStream(fis);
                    player = new Player(bis);
                    FlujoTotal = fis.available();
                    new Thread() {
                        public void run() {
                            try {
                                player.play();
                            } catch (Exception e) {
                                e.printStackTrace();

                            }
                        }
                    }.start();
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            } catch (JavaLayerException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_AgregarMusicaMouseReleased

    private void PausaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PausaMouseReleased
        if (file != null && player != null) {
            try {
                pausa = fis.available();
                player.close();
                player = null;
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_PausaMouseReleased

    private void PlayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseReleased
        try {
            if (file == null) {
            } else {
                fis = new FileInputStream(file);
                bis = new BufferedInputStream(fis);
                player = new Player(bis);
                fis.skip(FlujoTotal - pausa);
                new Thread() {
                    public void run() {
                        try {
                            player.play();
                        } catch (JavaLayerException e) {
                            e.printStackTrace();
                        }
                    }
                }.start();
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        } catch (JavaLayerException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_PlayMouseReleased

    private void StopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StopMouseReleased
        if (player != null) {
            reproductorTexto.setText("");
            player.close();
            reproductorTexto.setText("");
            file = null;
        }
    }//GEN-LAST:event_StopMouseReleased

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        jd_muroPrincipal.setVisible(false);
        jd_muroPersonal.setVisible(true);
        jd_muroPersonal.pack();
        jd_muroPersonal.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton9MouseClicked

    private void reproductorPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reproductorPrincipalMouseClicked
        reproductorMusical.setVisible(true);
        reproductorMusical.pack();
        reproductorMusical.setLocationRelativeTo(null);
    }//GEN-LAST:event_reproductorPrincipalMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        reproductorMusical.setVisible(true);
        reproductorMusical.pack();
        reproductorMusical.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        jd_muroPersonal.setVisible(false);
        jd_muroPrincipal.setVisible(true);
        jd_muroPrincipal.pack();
        jd_muroPrincipal.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton2MouseClicked

    private void bt_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseClicked
        administradorUsuario admin = new administradorUsuario("./UsuariosRegulares.pfb");
        for (Object usuario : admin.getUsuarios()) {
            System.out.println(((Regular) usuario).getNombre());
            if (tf_username.getText().equals(((Regular) usuario).getNombre()) && pf_password.getText().equals(((Regular) usuario).getContrasenia())) {
                System.out.println("1");
            }
        }
    }//GEN-LAST:event_bt_loginMouseClicked

    public void ReproductorMusical() {
        reproductorMusical.setVisible(true);
        reproductorMusical.pack();
        reproductorMusical.setLocationRelativeTo(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarMusica;
    private javax.swing.JButton Pausa;
    private javax.swing.JButton Play;
    private javax.swing.JButton Stop;
    private javax.swing.JButton bt_CreateNewAccount;
    private javax.swing.JButton bt_login;
    private javax.swing.JButton bt_registrarAdmin;
    private javax.swing.JButton bt_registrarteU;
    private javax.swing.JPanel header_register1;
    private javax.swing.JPanel header_registerAdmin;
    private javax.swing.JButton ingresarAdminsitrador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JDialog jd_createAdmin;
    private javax.swing.JDialog jd_createUser;
    private javax.swing.JDialog jd_muroPersonal;
    private javax.swing.JDialog jd_muroPrincipal;
    private javax.swing.JLabel lb_exitBttnAddAdmin;
    private javax.swing.JLabel lb_exitBttnRegister1;
    private javax.swing.JLabel lb_exitTxt;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JPasswordField pf_passwordConfirmAdmin;
    private javax.swing.JPasswordField pf_passwordConfirmU;
    private javax.swing.JPasswordField pf_passwordCreateAdmin;
    private javax.swing.JPasswordField pf_passwordCreateU;
    private javax.swing.JPanel pn_exitBttn;
    private javax.swing.JPanel pn_exitBttnAddAdmin;
    private javax.swing.JPanel pn_exitBttnRegister1;
    private javax.swing.JPanel pn_header;
    private javax.swing.JDialog reproductorMusical;
    private javax.swing.JButton reproductorPrincipal;
    private javax.swing.JLabel reproductorTexto;
    private javax.swing.JSpinner sp_dateAdmin;
    private javax.swing.JSpinner sp_dateU;
    private javax.swing.JSpinner sp_monthAdmin;
    private javax.swing.JSpinner sp_monthU;
    private javax.swing.JSpinner sp_yearAdmin;
    private javax.swing.JSpinner sp_yearU;
    private javax.swing.JTextField tf_apellidoAdmin;
    private javax.swing.JTextField tf_apellidoRegistrarU;
    private javax.swing.JTextField tf_apodoAdmin;
    private javax.swing.JTextField tf_apodoRegistrarU;
    private javax.swing.JTextField tf_nombreAdmin;
    private javax.swing.JTextField tf_nombreRegistrarU;
    private javax.swing.JTextField tf_paisAdmin;
    private javax.swing.JTextField tf_paisCreateU;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables

    public void LlenarEspacios() {

        if (tf_nombreRegistrarU.getText().equals("")) {
            tf_nombreRegistrarU.setText("Nombre");
            tf_nombreRegistrarU.setForeground(Color.gray);
        }
        if (tf_apellidoRegistrarU.getText().equals("")) {
            tf_apellidoRegistrarU.setText("Apellido");
            tf_apellidoRegistrarU.setForeground(Color.gray);
        }

        if (tf_apodoRegistrarU.getText().equals("")) {
            tf_apodoRegistrarU.setText("Apodo");
            tf_apodoRegistrarU.setForeground(Color.gray);
        }

        if (pf_passwordConfirmU.getText().equals("")) {
            pf_passwordConfirmU.setText("Contraseña");
            pf_passwordConfirmU.setForeground(Color.gray);
        }

        if (pf_passwordCreateU.getText().equals("")) {
            pf_passwordCreateU.setText("Contraseña");
            pf_passwordCreateU.setForeground(Color.gray);
        }

        if (tf_paisCreateU.getText().equals("")) {
            tf_paisCreateU.setText("País o región");
            tf_paisCreateU.setForeground(Color.gray);
        }
    }

    public void LlenarEspaciosAdmin() {

        if (tf_nombreAdmin.getText().equals("")) {
            tf_nombreAdmin.setText("Nombre");
            tf_nombreAdmin.setForeground(Color.gray);
        }
        if (tf_apellidoAdmin.getText().equals("")) {
            tf_apellidoAdmin.setText("Apellido");
            tf_apellidoAdmin.setForeground(Color.gray);
        }

        if (tf_apodoAdmin.getText().equals("")) {
            tf_apodoAdmin.setText("Apodo");
            tf_apodoAdmin.setForeground(Color.gray);
        }

        if (pf_passwordConfirmAdmin.getText().equals("")) {
            pf_passwordConfirmAdmin.setText("Contraseña");
            pf_passwordConfirmAdmin.setForeground(Color.gray);
        }

        if (pf_passwordCreateAdmin.getText().equals("")) {
            pf_passwordCreateAdmin.setText("Contraseña");
            pf_passwordCreateAdmin.setForeground(Color.gray);
        }

        if (tf_paisAdmin.getText().equals("")) {
            tf_paisAdmin.setText("País o región");
            tf_paisAdmin.setForeground(Color.gray);
        }
    }
}
